global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'csharp-ef-app'
    static_configs:
      - targets: ['csharp-ef-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'csharp-dapper-app'
    static_configs:
      - targets: ['csharp-dapper-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']